#!/bin/bash

CWD="$PWD"
filemap="/mnt/c/Users/$WINUSER/OneDrive/Coding/.gimmie/filemap.json"
argsmap="/mnt/c/Users/$WINUSER/OneDrive/Coding/.gimmie/argsmap.json"
execmap="/mnt/c/Users/$WINUSER/OneDrive/Coding/.gimmie/execmap.json"
program_name="$1"

if [ -z "$program_name" ]
then
	echo "$(cat "$filemap" | sed -E "s/.*\"([a-zA-Z_-]*)\" : \".*\".*/\1/;t;d")"
else
	program_dir=""
	program_dir="$(cat "$filemap" | sed -E "s/.*\""$program_name"\" : \"(.*)\".*/\1/;t;d")"
	to_exec=""
	to_exec="$(cat "$execmap" | sed -E "s/.*\""$program_name"\" : \"(.*)\".*/\1/;t;d")"
	args=""
	args="$(cat "$argsmap" | sed -E "s/.*\""$program_name"\" : \"(.*)\".*/\1/;t;d")"
	if [ -z "$program_dir" ]
	then
		2>&1 echo "no directory information found for $1 in filemap"
	else
		if [ -z "$args" ]
		then
			args="$program_name"
		fi
		(cd "$program_dir" && "$to_exec" "$args")
	fi
fi
