#!/bin/bash

PROGRAM_PATH='/mnt/c/Program Files/Notepad++/Notepad++.exe'

if [[ "$@" = "" ]]
then
	("$PROGRAM_PATH" &)
else
	for file in "$@"
	do
		(wslconvert "$file" | xargs "$PROGRAM_PATH" &)
	done
fi
